apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
  selector:
    app: python-fastapi-server
    type: backend
